# Generated by Django 3.1.7 on 2021-03-13 13:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bitcoin_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='ethereum_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))]),
        ),
    ]
