# Generated by Django 3.1.7 on 2021-03-13 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20210313_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EOS_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AddField(
            model_name='user',
            name='cardano_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AddField(
            model_name='user',
            name='dogecoin_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AddField(
            model_name='user',
            name='litecoin_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AddField(
            model_name='user',
            name='monero_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AddField(
            model_name='user',
            name='neo_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AddField(
            model_name='user',
            name='polkadot_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AddField(
            model_name='user',
            name='stellar_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AddField(
            model_name='user',
            name='terra_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AddField(
            model_name='user',
            name='veChain_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bitcoin_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-08)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='ethereum_balance',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
    ]
