# Generated by Django 3.1.7 on 2021-03-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading_pairs', '0002_tradingpair_web_socket_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=290)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trading_pairs.tradingpair')),
            ],
        ),
    ]
