# Generated by Django 3.1.7 on 2021-03-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bull_or_bear',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
