# Generated by Django 3.1.7 on 2021-03-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_pairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='web_socket_url',
            field=models.CharField(default='XXXXXXX', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
