# Generated by Django 3.1.7 on 2021-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_pairs', '0002_tradingpair_web_socket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='total_suppy',
            field=models.IntegerField(blank=True, default=500),
            preserve_default=False,
        ),
    ]
