# Generated by Django 3.1.7 on 2021-03-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_pairs', '0003_tradingpair_total_suppy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingpair',
            name='web_socket_url',
        ),
    ]
