# Generated by Django 3.1.7 on 2021-03-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_pairs', '0004_remove_tradingpair_web_socket_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='total_suppy',
            field=models.BigIntegerField(blank=True),
        ),
    ]
